# This is a basic workflow to help you get started with Actions

name: Build And Publish Blog

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: check modified files
        id: check_files
        run: |
          echo "::set-output name=run_job::true"
    

      # Runs a single command using the runners shell
      - name: Install Package
        run: |
          if [[ ${{steps.check_files.outputs.run_job == true}} ]]; then
            exit 0
          fi
          npm install -g hexo-cli && npm install

      - name: Generate Html File
        run: |
          if [[ ${{steps.check_files.outputs.run_job == true}} ]]; then
            exit 0
          fi
          hexo g

      # Runs a set of commands using the runners shell
      - name: Deploy To RepoðŸš€
        if: ${{ github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PUBLSH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
      - name: Upload to Collect Repo
        if: ${{ github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.PUBLSH_TOKEN }}
          BRANCH: build-${{ github.run_id }} # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.